<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class eventosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('eventos')->insert([
            [
                'nombre' => 'Concierto',
                'hora' => '20:00',
                'fecha' => '2024-05-26',
                'localizacion' => 'Plaza Toros',
                'idOrganizador' => 1,
                'idCiudad' => 3,
                'aforoTotal' => 30000,
                'aforoDisponible' => 30000,
                'idCategoria' => 1,
                'descripcion' => 'Concierto de Alejandro Sanz disco sirope',
                'precio' => 50,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Feria de Sevilla',
                'hora' => '18:00',
                'fecha' => '2024-04-15',
                'localizacion' => 'Recinto Ferial',
                'idOrganizador' => 1,
                'idCiudad' => 1,
                'aforoTotal' => 50000,
                'aforoDisponible' => 50000,
                'idCategoria' => 1,
                'descripcion' => 'Feria de Abril en Sevilla con casetas y atracciones',
                'precio' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Exposición de Arte',
                'hora' => '10:00',
                'fecha' => '2024-06-10',
                'localizacion' => 'Museo del Prado',
                'idOrganizador' => 1,
                'idCiudad' => 2,
                'aforoTotal' => 2000,
                'aforoDisponible' => 2000,
                'idCategoria' => 1,
                'descripcion' => 'Exposición de las obras de Velázquez',
                'precio' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Partido de Fútbol',
                'hora' => '21:00',
                'fecha' => '2024-07-01',
                'localizacion' => 'Estadio Santiago Bernabéu',
                'idOrganizador' => 1,
                'idCiudad' => 4,
                'aforoTotal' => 80000,
                'aforoDisponible' => 80000,
                'idCategoria' => 1,
                'descripcion' => 'Partido entre Real Madrid y Barcelona',
                'precio' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Festival de Jazz',
                'hora' => '19:00',
                'fecha' => '2024-08-20',
                'localizacion' => 'Auditorio Nacional',
                'idOrganizador' => 1,
                'idCiudad' => 2,
                'aforoTotal' => 10000,
                'aforoDisponible' => 10000,
                'idCategoria' => 1,
                'descripcion' => 'Festival de Jazz con artistas internacionales',
                'precio' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Obra de Teatro',
                'hora' => '20:30',
                'fecha' => '2024-09-15',
                'localizacion' => 'Teatro Real',
                'idOrganizador' => 1,
                'idCiudad' => 3,
                'aforoTotal' => 1500,
                'aforoDisponible' => 1500,
                'idCategoria' => 1,
                'descripcion' => 'Representación de Hamlet por la compañía nacional de teatro',
                'precio' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Carrera Popular',
                'hora' => '09:00',
                'fecha' => '2024-10-05',
                'localizacion' => 'Parque Retiro',
                'idOrganizador' => 1,
                'idCiudad' => 4,
                'aforoTotal' => 20000,
                'aforoDisponible' => 20000,
                'idCategoria' => 1,
                'descripcion' => 'Carrera popular de 10km por el centro de Madrid',
                'precio' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Concierto de Rock',
                'hora' => '21:00',
                'fecha' => '2024-11-22',
                'localizacion' => 'Wizink Center',
                'idOrganizador' => 1,
                'idCiudad' => 4,
                'aforoTotal' => 17000,
                'aforoDisponible' => 17000,
                'idCategoria' => 1,
                'descripcion' => 'Concierto de la banda de rock Foo Fighters',
                'precio' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Feria del Libro',
                'hora' => '10:00',
                'fecha' => '2024-12-05',
                'localizacion' => 'IFEMA',
                'idOrganizador' => 1,
                'idCiudad' => 4,
                'aforoTotal' => 30000,
                'aforoDisponible' => 30000,
                'idCategoria' => 1,
                'descripcion' => 'Feria del libro con presentaciones de autores y firmas',
                'precio' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Festival de Cine',
                'hora' => '18:00',
                'fecha' => '2024-09-30',
                'localizacion' => 'Cines Callao',
                'idOrganizador' => 1,
                'idCiudad' => 4,
                'aforoTotal' => 5000,
                'aforoDisponible' => 5000,
                'idCategoria' => 1,
                'descripcion' => 'Festival internacional de cine con proyecciones y galas',
                'precio' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
